konnectors/cozy-konnector-sosh

- src/index.js
- GET new login form to get cookies, auth id & fisrt XSRF token
- POST to new XHR login selection endpoint to get second XSRF token
- POST to new XHR password endpoint to effectively sign in
> fix: Honor new Sosh login flow

- src/index.js
This PR add the CookieKonnector base to manage session.
Big diff because all lines are newly indented
> feat: Add session management

- src/index.js
This PR prevents the konnector from crashing when there is no moreBillsButton to click during bills srcaping (when there is not enough bills to be covered by the button for example)
> feat: Improve bills scraping when there is no moreBills button

- src/index.js
instead of the pilot since the pilot is on about:blank which make
window.crypto not available.
- fix: Now use crypto on the worker
- feat: More logs
> fix: Now use crypto on the worker

- src/index.js
- fix: lint
- fix: Set all debug log as info
- fix: Avoid switch to sosh or orange iphone app while running sosh konnector
> fix: Avoid switch to sosh or orange iphone app while running sosh konnector

- src/index.js
- src/interceptor.js
- detect sosh only account
- rework and simplify login phase
- extract xhr requests interception
- download files with downloadFileInWorker
> fix: Full konnector rework

- src/index.js
- fix: Now wait for the change account button to be ready
- fix: Credentials interception
> fix: Now wait for the change account button to be ready

- src/index.js
And throw VENDOR_DOWN in this case.
Also added a PromiseRaceWithError method to race promises but with a
specific error message when one of the promises fail before the resolve.
This may make it easier to debug with this error message.
> feat: Check specific error page on login

- src/index.js
This PR fixes the credentials interception and usage.
It also ensure a thinner logout verifications.
> fix: Fix credentials interceptions & autoLogin/logout

- src/index.js
This PR fixes the case where the morBillsButton does not exists. It may occurs for user that do not have more than 12 bills to fetch.
> feat: Use a checking function instead of waiting for moreBillsButton

- src/index.js
Due to a user test, we notify a new homePage problematic when the user has more than one contract (mobile/internet for example, or several phoneLines) Leading to the crash of the konnector. This PR tries to fix it by verifying if a choice has to be made after the login. If so we're clicking on the first contract, fetch it, then come back on the homePage to select the next one.
But there's a catch, we didn't really know how the choice is made once a first contract has been already selected, so we're trying to find a button we can click, but not sure it's the right way to do.
> feat: Handle multiple contracts

- src/index.js
There was a change in the sosh website naviation regarding personal information
> fix: Adaptation to identity navigation change

- src/index.js
- fix: Timeout adjustments
- fix: waitforundefinedreallyclick should return true in the end
- fix: Clean unused code
- fix: Wrong identification key
> fix: some small adjustments after review and test

- src/index.js
Since it is not possible to autologin anymore, do not force
ensureNotAuthenticated when it is not needed.
We save a unique id which is easy to retrieve in credentials to make it
easy to compare with current unique user id.- fix: Fix email structure in identity and rename houseNumber
> [SCR-275] fix: Logout only when needed

- src/index.js
We need to wait for a first user interaction before filling the login or
password field. That is why wait for the user to click on the login
field before filling it, or else sosh will act as if the field was not
filled.
- fix: always get userId from correct worker session
> [SCR-285] feat: Add autofill of the user identifiers

- src/index.js
This adds the same autoFill and logout method used in Orange konnectors, it was forgotten when the konnectors has been modified last time. It ensure a good logout and automatic fill of the credential when the user has select the input. This was causing issues on several users, as the website where detecting the filling had not been made by a human.
It also fix uncompleted identity fetching due to intercepted JSON structure changes.
It also remove the not used anymore function "autoLogin" and rename the autoFill function to be more explicite. It also add some starting log for a better debug.
> [SCR-400] [SCR-401] Fix/website changes

- src/index.js
This PR adds numerous check to avoid silent error, causing the konnector to finish in success while fetching nothing despite having bills to save.
I have also added a log with every keys in the intercepted object supposed to contains the list of recentBills, to see if the structure change from a user to another. Not being personnal info, I think it's ok but don't hesitate to make me remove that if you think it's not a good idea.
> [SCR-152] feat: Avoid silent error on bills scraping

- src/index.js
This PR adds the handling for mobileConnect method, it was not implemented on the Sosh website until now, so konnector's update is needed.
It also adds an Orange account detection in case the user is trying to log in with an Orange account. Detection occurs when checking the contract. Contracts are filtered to return only Sosh's ones, if no contracts return at all, it mean the user is using his orange account. Execution is terminated properly to avoid error and a warning is dispatched for us to know why the konnector did not download any bills.
> [SCR-741] Fix/handle mobile connect

- src/index.js
Change the billsPage selector to ensure a better detection when bills page is fully loaded
> fix: Change bills page detection selector

- src/index.js
Changes on the website has been made, using shadowRoots elements to host login and logout buttons.
> fix: Use of shadowRoot elements for login/logout
